### ISSUE TITLE
SPFx SPHelperCommon function misspelled

### ISSUE THREAD

**Issue by Aryo777** [SumitKanchan4/SPFx#1]
Hi Sumit,
i was checking out your image library and while deploying it on my tenant i had some issues. What i found was that the function call for "isStringNullOrEmpty" is mispelled in the SPListOperations.js and the image-gallery-web-part.js -> It is written "isStringNullOrEmpy" and missing a "t". I forked your project and wanted to fix it myself but i am new to github and still learning how pull request and everything works. So i decided to leave you an issue here ;) 

Your image library looks very nice, keep up the good work!

**Comment by SumitKanchan4** [comment]
Hi Aryo,

Thanks for using the component and reporting the issue. But I have resolved the issue in the previous release. Try checking the latest package of the spfxhelper in the image library component. I'll be happy to help you if you still face the issue. 

Regards,
Sumit Kanchan

**Comment by SumitKanchan4** [comment]
I am closing the issue. please re-open the issue or you can mail me directly to sumit.kanchan04@live.com if you need any help.
